### ISSUE TITLE
attrap unusable due to syntax error

### ISSUE THREAD

**Issue by svenpanne** [jyp/attrap#13]
https://github.com/jyp/attrap/commit/58ac51542ced1c7a3c22d4f23f6ca58358587748 totally broke things due to unbalanced parentheses.

**Comment by jyp** [comment]
Should be fixed by now

**Comment by svenpanne** [comment]
Thanks for the quick fix! I've just re-updated my Spacemacs packages and the error has vanished.

Just out of curiosity: Spacemacs pulls its packages from various package archives, e.g. MELPA. Do you have to explicitly release a new version or do you get the latest & greatest commit automatically? Probably the latter, I guess, right?

**Comment by jyp** [comment]
Right, melpa pulls from the master branch. I'm considering to make a `dev` branch and push to the master branch to make releases.
