### ISSUE TITLE
Support for hlint checker

### ISSUE THREAD

**Issue by patrl** [jyp/attrap#7]
It would be great if `attrap` supported the haskell `hlint` checker. There is already [hlint-refactor-mode](https://github.com/mpickering/hlint-refactor-mode/blob/master/hlint-refactor.el), which implements this, but it's great to see a more general solution for supporting refactoring suggestions.

**Comment by jyp** [comment]
I'll merge a pull request. But since I do not use hlint, I don't think I should attempt to to this.

**Comment by jyp** [comment]
Duplicate of #9
