### ISSUE TITLE
Feature Request: Add auto-fix for hlint

### ISSUE THREAD

**Issue by Fresheyeball** [jyp/attrap#9]
Auto fix for ghc suggestions is very nice. The auto fix behavior could get even beefier by supporting hlint fixes.

**Comment by IQubic** [comment]
What is the status on this? Is there any way for to get Attrap to work with hlint?

**Comment by jyp** [comment]
I'll merge a pull request. But since I do not use hlint, I don't think I should attempt to to this.

**Comment by jyp** [comment]
I've implemented this.
